export const utilscommands: {
  urllogo: string;
  bg: string;
  color: string;
  id: string;
  name: string;
}[] = [
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/217/Orlando_Magic/',
    bg: '#C2CCD2',
    color: '#0B77BD',
    id: 'ORL',
    name: 'Orlando Magic',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/218/Philadelphia_76ers/',
    bg: '#1D428A',
    color: '#FFFFFF',
    id: 'PHI',
    name: 'Philadelphia 76ers',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/238/Phoenix_Suns/',
    bg: '#F9A01B',
    color: '#000000',
    id: 'PHO',
    name: 'Phoenix Suns',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/239/Portland_Trail_Blazers/',
    bg: '#FFFFFF',
    color: '#CF0A2C',
    id: 'POR',
    name: 'Portland Trail Blazers',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/240/Sacramento_Kings/',
    bg: '#5B2B82',
    color: '#FFFFFF',
    id: 'SAC',
    name: 'Sacramento Kings',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/233/San_Antonio_Spurs/',
    bg: '#FFFFFF',
    color: '#000000',
    id: 'SAS',
    name: 'San Antonio Spurs',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/227/Toronto_Raptors/',
    bg: '#000000',
    color: '#BD1B21',
    id: 'TOR',
    name: 'Toronto Raptors',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/234/Utah_Jazz/',
    bg: '#FFFFFF',
    color: '#000000',
    id: 'UTA',
    name: 'Utah Jazz',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/219/Washington_Wizards/',
    bg: '#E31837',
    color: '#002B5C',
    id: 'WAS',
    name: 'Washington Wizards',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/220/Atlanta_Hawks/',
    bg: '#FFFFFF',
    color: '#C8102E',
    id: 'ATL',
    name: 'Atlanta Hawks',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/213/Boston_Celtics/',
    bg: '#008248',
    color: '#FFFFFF',
    id: 'BOS',
    name: 'Boston Celtics',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/3786/Brooklyn_Nets/',
    bg: '#061922',
    color: '#FEFEFE',
    id: 'BRK',
    name: 'Brooklyn Nets',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/221/Chicago_Bulls/',
    bg: '#CE1141',
    color: '#000000',
    id: 'CHI',
    name: 'Chicago Bulls',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/5120/Charlotte_Hornets/',
    bg: '#00788C',
    color: '#1D1160',
    id: 'CHO',
    name: 'Charlotte Hornets',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/222/Cleveland_Cavaliers/',
    bg: '#6F243A',
    color: '#FEB11E',
    id: 'CLE',
    name: 'Cleveland Cavaliers',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/228/Dallas_Mavericks/',
    bg: '#007DC5',
    color: '#FFFFFF',
    id: 'DAL',
    name: 'Dallas Mavericks',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/229/Denver_Nuggets/',
    bg: '#0D2240',
    color: '#FFC627',
    id: 'DEN',
    name: 'Denver Nuggets',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/223/Detroit_Pistons/',
    bg: '#C8102E',
    color: '#FFFFFF',
    id: 'DET',
    name: 'Detroit Pistons',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/235/Golden_State_Warriors/',
    bg: '#FDB927',
    color: '#1D428A',
    id: 'GSW',
    name: 'Golden State Warriors',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/230/Houston_Rockets/',
    bg: '#F00840',
    color: '#333733',
    id: 'HOU',
    name: 'Houston Rockets',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/224/Indiana_Pacers/',
    bg: '#FDBB30',
    color: '#002D62',
    id: 'IND',
    name: 'Indiana Pacers',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/236/Los_Angeles_Clippers/',
    bg: '#FFFFFF',
    color: '#C8102E',
    id: 'LAC',
    name: 'Los Angeles Clippers',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/237/Los_Angeles_Lakers/',
    bg: '#552583',
    color: '#FDB927',
    id: 'LAL',
    name: 'Los Angeles Lakers',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/231/Memphis_Grizzlies/',
    bg: '#5D76A9',
    color: '#12173F',
    id: 'MEM',
    name: 'Memphis Grizzlies',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/214/Miami_Heat/',
    bg: '#FFFFFF',
    color: '#98002E',
    id: 'MIA',
    name: 'Miami Heat',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/225/Milwaukee_Bucks/',
    bg: '#00471B',
    color: '#EEE1C6',
    id: 'MIL',
    name: 'Milwaukee Bucks',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/232/Minnesota_Timberwolves/',
    bg: '#236192',
    color: '#0C2340',
    id: 'MIN',
    name: 'Minnesota Timberwolves',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/4962/New_Orleans_Pelicans/',
    bg: '#0A2240',
    color: '#8C734B',
    id: 'NOP',
    name: 'New Orleans Pelicans',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/216/New_York_Knicks/',
    bg: '#F58426',
    color: '#1D428A',
    id: 'NYK',
    name: 'New York Knicks',
  },
  {
    urllogo: 'https://www.sportslogos.net/logos/list_by_team/2687/Oklahoma_City_Thunder/',
    bg: '#007AC1',
    color: '#F05133',
    id: 'OKC',
    name: 'Oklahoma City Thunder',
  },
];
