export const utilscommands: { bg: string; color: string; id: string; name: string }[] = [
  { bg: '#C2CCD2', color: '#0B77BD', id: 'ORL', name: 'Orlando Magic' },
  { bg: '#1D428A', color: '#FFFFFF', id: 'PHI', name: 'Philadelphia 76ers' },
  { bg: '#F9A01B', color: '#000000', id: 'PHO', name: 'Phoenix Suns' },
  { bg: '#FFFFFF', color: '#CF0A2C', id: 'POR', name: 'Portland Trail Blazers' },
  { bg: '#5B2B82', color: '#FFFFFF', id: 'SAC', name: 'Sacramento Kings' },
  { bg: '#FFFFFF', color: '#000000', id: 'SAS', name: 'San Antonio Spurs' },
  { bg: '#000000', color: '#BD1B21', id: 'TOR', name: 'Toronto Raptors' },
  { bg: '#FFFFFF', color: '#000000', id: 'UTA', name: 'Utah Jazz' },
  { bg: '#E31837', color: '#002B5C', id: 'WAS', name: 'Washington Wizards' },
  { bg: '#FFFFFF', color: '#C8102E', id: 'ATL', name: 'Atlanta Hawks' },
  { bg: '#008248', color: '#FFFFFF', id: 'BOS', name: 'Boston Celtics' },
  { bg: '#061922', color: '#FEFEFE', id: 'BRK', name: 'Brooklyn Nets' },
  { bg: '#CE1141', color: '#000000', id: 'CHI', name: 'Chicago Bulls' },
  { bg: '#00788C', color: '#1D1160', id: 'CHO', name: 'Charlotte Hornets' },
  { bg: '#6F243A', color: '#FEB11E', id: 'CLE', name: 'Cleveland Cavaliers' },
  { bg: '#007DC5', color: '#FFFFFF', id: 'DAL', name: 'Dallas Mavericks' },
  { bg: '#0D2240', color: '#FFC627', id: 'DEN', name: 'Denver Nuggets' },
  { bg: '#C8102E', color: '#FFFFFF', id: 'DET', name: 'Detroit Pistons' },
  { bg: '#FDB927', color: '#1D428A', id: 'GSW', name: 'Golden State Warriors' },
  { bg: '#F00840', color: '#333733', id: 'HOU', name: 'Houston Rockets' },
  { bg: '#FDBB30', color: '#002D62', id: 'IND', name: 'Indiana Pacers' },
  { bg: '#FFFFFF', color: '#C8102E', id: 'LAC', name: 'Los Angeles Clippers' },
  { bg: '#552583', color: '#FDB927', id: 'LAL', name: 'Los Angeles Lakers' },
  { bg: '#5D76A9', color: '#12173F', id: 'MEM', name: 'Memphis Grizzlies' },
  { bg: '#FFFFFF', color: '#98002E', id: 'MIA', name: 'Miami Heat' },
  { bg: '#00471B', color: '#EEE1C6', id: 'MIL', name: 'Milwaukee Bucks' },
  { bg: '#236192', color: '#0C2340', id: 'MIN', name: 'Minnesota Timberwolves' },
  { bg: '#0A2240', color: '#8C734B', id: 'NOP', name: 'New Orleans Pelicans' },
  { bg: '#F58426', color: '#1D428A', id: 'NYK', name: 'New York Knicks' },
  { bg: '#007AC1', color: '#F05133', id: 'OKC', name: 'Oklahoma City Thunder' },
];
