export const utilsteamstables = [
  { id: '', type: '', link: 'stats_basic_totals.html' },
  { id: '', type: '', link: 'stats_per_game_totals.html' },
  { id: '', type: '', link: 'opp_stats_basic_totals.html' },
  { id: '', type: '', link: 'opp_stats_per_game_totals.html' },
  { id: '', type: '', link: 'stats_basic_ranks.html' },
  { id: '', type: '', link: 'stats_per_game_ranks.html' },
  { id: '', type: '', link: 'opp_stats_basic_ranks.html' },
  { id: '', type: '', link: 'opp_stats_per_game_ranks.html' },
  { id: '', type: '', link: 'stats_basic_yr_yr.html' },
  { id: '', type: '', link: 'stats_per_game_yr_yr.html' },
  { id: '', type: '', link: 'opp_stats_basic_yr_yr.html' },
  { id: '', type: '', link: 'opp_stats_per_game_yr_yr.html' },
  { id: '', type: '', link: 'leaders_season.html' },
  { id: '', type: '', link: 'leaders_career.html' },
  { id: '', type: '', link: 'players.html' },
  { id: '', type: '', link: 'coaches.html' },
  { id: '', type: '', link: 'executives.html' },
  { id: '', type: '', link: 'all_star.html' },
  { id: '', type: '', link: 'hof.html' },
  { id: '', type: '', link: 'draft.html' },
  { id: '', type: '', link: 'numbers.html' },
  { id: '', type: '', link: 'head2head.html' },
];
