export const utilsplayerstables: { id: string; text: string }[] = [
  { id: 'per_game', text: 'За игру.Регулярный сезон' },
  { id: 'playoffs_per_game', text: 'За игру.Плей-офф' },
  { id: 'totals', text: 'Итоги.Регулярный сезон' },
  { id: 'playoffs_totals', text: 'Итоги.Плей-офф' },
  { id: 'per_minute', text: 'За 36 минут.Регулярный сезон' },
  { id: 'playoffs_per_minute', text: 'За 36 минут.Плей-офф' },
  { id: 'per_poss', text: 'За 100 владений мячом.Регулярный сезон' },
  { id: 'playoffs_per_poss', text: 'За 100 владений мячом.Плей-офф' },
  { id: 'advanced', text: 'Дополнительно.Регулярный сезон' },
  { id: 'playoffs_advanced', text: 'Дополнительно.Плей-офф' },
  { id: 'adj_shooting', text: 'Скорректированная стрельба' },
  { id: 'pbp', text: 'Игра за игру.Регулярный сезон' },
  { id: 'playoffs_pbp', text: 'Игра за игру.Плей-офф' },
  { id: 'shooting', text: 'Броски.Регулярный сезон' },
  { id: 'playoffs_shooting', text: 'Броски.Плей-офф' },
  { id: 'highs-reg-season', text: 'Игровые максимумы.Регулярный сезон' },
  { id: 'highs-playoffs', text: 'Игровые максимумы.Плей-офф' },
  { id: 'playoffs-series', text: 'Серия плей-офф' },
  { id: 'all_star', text: 'Матчи всех звезд' },
  { id: 'sims-thru', text: 'Баллы сходства.За определенный период' },
  { id: 'sims-career', text: 'Баллы сходства.За карьеру' },
  { id: 'all_college_stats', text: 'Статистика колледжа' },
  { id: 'all_salaries', text: 'Зарплаты' },
];
