import { MasLeaguesPagesType } from 'mas';

export const masleaguespages: MasLeaguesPagesType[] = [
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Средние показатели по лиге НБА.За игру',
    link: 'NBA_stats_per_game.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Средние показатели по лиге НБА.Итоги',
    link: 'NBA_stats_totals.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Средние показатели по лиге НБА.За 100 владений мячом',
    link: 'NBA_stats_per_poss.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Средние показатели по лиге ABA.За игру',
    link: 'ABA_stats_per_game.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Средние показатели по лиге ABA.Итоги',
    link: 'ABA_stats_totals.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Средние показатели по лиге ABA.За 100 владений мячом',
    link: 'ABA_stats_per_poss.html',
  },
  {
    heading: null,
    id: 'active_franchises',
    type: 'table',
    name: 'Средние показатели по лиге НБА.Действующие франшизы',
    link: 'NBA_wins.html',
  },
  {
    heading: null,
    id: 'defunct_franchises',
    type: 'table',
    name: 'Средние показатели по лиге НБА.Несостоявшиеся франшизы',
    link: 'NBA_wins.html',
  },
  {
    heading: null,
    id: 'active_franchises',
    type: 'table',
    name: 'Средние показатели по лиге ABA.Действующие франшизы',
    link: 'ABA_wins.html',
  },
  {
    heading: null,
    id: 'defunct_franchises',
    type: 'table',
    name: 'Средние показатели по лиге ABA.Несостоявшиеся франшизы',
    link: 'ABA_wins.html',
  },
  {
    heading: null,
    id: 'best_records',
    type: 'record',
    name: 'Средние показатели по лиге НБА.Лучшие рекорды',
    link: 'NBA_best_records.html',
  },
  {
    heading: null,
    id: 'best_records',
    type: 'record',
    name: 'Средние показатели по лиге ABA.Лучшие рекорды',
    link: 'ABA_best_records.html',
  },
  {
    heading: null,
    id: 'worst_records',
    type: 'record',
    name: 'Средние показатели по лиге НБА.Худшие рекорды',
    link: 'NBA_worst_records.html',
  },
  {
    heading: null,
    id: 'worst_records',
    type: 'record',
    name: 'Средние показатели по лиге ABA.Худшие рекорды',
    link: 'ABA_worst_records.html',
  },
];
