import { MasLeaguesYearsType } from 'mas';

export const masleaguesyears: MasLeaguesYearsType[] = [
  {
    id: 'confs_standings_E',
    type: 'table',
    name: 'Турнирная таблица.Восточная конференция',
    link: '.html',
  },
  {
    id: 'confs_standings_W',
    type: 'table',
    name: 'Турнирная таблица.Западная конференция',
    link: '.html',
  },
  {
    id: 'per_game-team',
    type: 'table',
    name: 'Статистика за игру.Команда',
    link: '.html',
  },
  {
    id: 'per_game-opponent',
    type: 'table',
    name: 'Статистика за игру.Оппонент',
    link: '.html',
  },
  {
    id: 'totals-team',
    type: 'table',
    name: 'Статистика итогов.Команда',
    link: '.html',
  },
  {
    id: 'totals-opponent',
    type: 'table',
    name: 'Статистика итогов.Оппонент',
    link: '.html',
  },
  {
    id: 'per_poss-team',
    type: 'table',
    name: 'Статистика за 100 владений мячом.Команда',
    link: '.html',
  },
  {
    id: 'per_poss-opponent',
    type: 'table',
    name: 'Статистика за 100 владений мячом.Оппонент',
    link: '.html',
  },
  {
    id: 'advanced-team',
    type: 'table',
    name: 'Статистика дополнительно.Команда',
    link: '.html',
  },
  {
    id: 'shooting-team',
    type: 'table',
    name: 'Статистика бросков.Команда',
    link: '.html',
  },
  {
    id: 'shooting-opponent',
    type: 'table',
    name: 'Статистика бросков.Оппонент',
    link: '.html',
  },
  {
    id: 'all_awards',
    type: 'table',
    name: 'Награды сезона лиги',
    link: '.html',
  },
  {
    id: 'div_leaders',
    type: 'table',
    name: 'Лидеры сезона лиги',
    link: '.html',
  },
  {
    id: 'all-nba_1',
    type: 'tablep',
    name: 'All-NBA.Первая команда',
    link: '.html',
  },
  {
    id: 'all-nba_2',
    type: 'tablep',
    name: 'All-NBA.Вторая команда',
    link: '.html',
  },
  {
    id: 'all-nba_3',
    type: 'tablep',
    name: 'All-NBA.Третья команда',
    link: '.html',
  },
  {
    id: 'all-defensive_1',
    type: 'tablep',
    name: 'All-Defensive.Первая команда',
    link: '.html',
  },
  {
    id: 'all-defensive_2',
    type: 'tablep',
    name: 'All-Defensive.Вторая команда',
    link: '.html',
  },
  {
    id: 'all-rookie_1',
    type: 'tablep',
    name: 'All-Rookie.Первая команда',
    link: '.html',
  },
  {
    id: 'all-rookie_2',
    type: 'tablep',
    name: 'All-Rookie.Вторая команда',
    link: '.html',
  },
  {
    id: 'all_star_game_rosters_1',
    type: 'tablep',
    name: 'Списки участников Матча всех звезд.Восточная конференция',
    link: '.html',
  },
  {
    id: 'all_star_game_rosters_2',
    type: 'tablep',
    name: 'Списки участников Матча всех звезд.Западная конференция',
    link: '.html',
  },
  {
    id: 'expanded_standings',
    type: 'table',
    name: 'Расширенная турнирная таблица',
    link: '_standings.html',
  },
  {
    id: 'team_vs_team',
    type: 'table',
    name: 'Команда против команды',
    link: '_standings.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Октябрь',
    link: '_games-october.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Ноябрь',
    link: '_games-november.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Декабрь',
    link: '_games-december.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Январь',
    link: '_games-january.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Февраль',
    link: '_games-february.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Март',
    link: '_games-march.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Апрель',
    link: '_games-april.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Май',
    link: '_games-may.html',
  },
  {
    id: 'schedule',
    type: 'schedule',
    name: 'Расписание.Июнь',
    link: '_games-june.html',
  },
  {
    id: 'div_leaders',
    type: 'table',
    name: 'Лидеры сезона',
    link: '_leaders.html',
  },
  { id: 'NBA_coaches', type: 'table', name: 'Тренеры', link: '_coaches.html' },
  {
    id: 'totals_stats',
    type: 'table',
    name: 'Итоговые показатели игроков',
    link: '_totals.html',
  },
  {
    id: 'per_game_stats',
    type: 'table',
    name: 'Игрок за игру',
    link: '_per_game.html',
  },
  {
    id: 'per_minute_stats',
    type: 'table',
    name: 'Игрок за 36 минут',
    link: '_per_minute.html',
  },
  {
    id: 'per_poss_stats',
    type: 'table',
    name: 'Игрок на 100 очков',
    link: '_per_poss.html',
  },
  {
    id: 'advanced_stats',
    type: 'table',
    name: 'Дополнительно',
    link: '_advanced.html',
  },
  { id: 'pbp_stats', type: 'table', name: 'Игроки', link: '_play-by-play.html' },
  { id: 'shooting_stats', type: 'table', name: 'Броски', link: '_shooting.html' },
  {
    id: 'adj-shooting',
    type: 'table',
    name: 'Скорректированные броски',
    link: '_adj_shooting.html',
  },
  {
    id: 'rookies',
    type: 'table',
    name: 'Новобранцы.Карьера',
    link: '_rookies.html',
  },
  {
    id: 'rookies',
    type: 'table',
    name: 'Новобранцы.Сезонная статистика',
    link: '_rookies-season-stats.html',
  },
  { id: 'final', type: 'table', name: 'Финал', link: '_final.html' },
  { id: 'ratings', type: 'table', name: 'Рейтинги команд', link: '_ratings.html' },
  {
    id: 'div_leaderboard',
    type: 'grid',
    name: 'Номера униформы',
    link: '_numbers.html',
  },
  { id: 'transactions', type: 'transactions', name: 'Транзакции', link: '_transactions.html' },
];
