import { MasType } from 'mas';

export const masplayers: MasType[] = [
  {
    heading: 'Жирным шрифтом выделен лидер лиги',
    link: 'per_game',
    type: 'table',
    id: 'per_game',
    name: 'За игру.Регулярный сезон',
  },
  {
    heading: 'Жирным шрифтом выделен лидер лиги',
    link: 'playoffs_per_game',
    type: 'table',
    id: 'playoffs_per_game',
    name: 'За игру.Плей-офф',
  },
  {
    heading: 'Жирным шрифтом выделен лидер лиги',
    link: 'totals',
    type: 'table',
    id: 'totals',
    name: 'Итоги.Регулярный сезон',
  },
  {
    heading: 'Жирным шрифтом выделен лидер лиги',
    link: 'playoffs_totals',
    type: 'table',
    id: 'playoffs_totals',
    name: 'Итоги.Плей-офф',
  },
  {
    heading: null,
    link: 'per_minute',
    type: 'table',
    id: 'per_minute',
    name: 'За 36 минут.Регулярный сезон',
  },
  {
    heading: null,
    link: 'playoffs_per_minute',
    type: 'table',
    id: 'playoffs_per_minute',
    name: 'За 36 минут.Плей-офф',
  },
  {
    heading: null,
    link: 'per_poss',
    type: 'table',
    id: 'per_poss',
    name: 'За 100 владений мячом.Регулярный сезон',
  },
  {
    heading: null,
    link: 'playoffs_per_poss',
    type: 'table',
    id: 'playoffs_per_poss',
    name: 'За 100 владений мячом.Плей-офф',
  },
  {
    heading: 'Жирным шрифтом выделен лидер лиги',
    link: 'advanced',
    type: 'table',
    id: 'advanced',
    name: 'Дополнительно.Регулярный сезон',
  },
  {
    heading: 'Жирным шрифтом выделен лидер лиги',
    link: 'playoffs_advanced',
    type: 'table',
    id: 'playoffs_advanced',
    name: 'Дополнительно.Плей-офф',
  },
  {
    heading: null,
    link: 'adj_shooting',
    type: 'table',
    id: 'adj_shooting',
    name: 'Скорректированная стрельба',
  },
  { heading: null, link: 'pbp', type: 'table', id: 'pbp', name: 'Игра за игру.Регулярный сезон' },
  {
    heading: null,
    link: 'playoffs_pbp',
    type: 'table',
    id: 'playoffs_pbp',
    name: 'Игра за игру.Плей-офф',
  },
  {
    heading: null,
    link: 'shooting',
    type: 'table',
    id: 'shooting',
    name: 'Броски.Регулярный сезон',
  },
  {
    heading: null,
    link: 'playoffs_shooting',
    type: 'table',
    id: 'playoffs_shooting',
    name: 'Броски.Плей-офф',
  },
  {
    heading: null,
    link: 'highs-reg-season',
    type: 'table',
    id: 'highs-reg-season',
    name: 'Игровые максимумы.Регулярный сезон',
  },
  {
    heading: null,
    link: 'highs-playoffs',
    type: 'table',
    id: 'highs-playoffs',
    name: 'Игровые максимумы.Плей-офф',
  },
  {
    heading: null,
    link: 'playoffs-series',
    type: 'table',
    id: 'playoffs-series',
    name: 'Серия плей-офф',
  },
  { heading: null, link: 'all_star', type: 'table', id: 'all_star', name: 'Матчи всех звезд' },
  {
    heading: 'Наиболее схожая дуга производительности',
    link: 'sims-thru',
    type: 'table',
    id: 'sims-thru',
    name: 'Баллы сходства.За определенный период',
  },
  {
    heading: 'Наиболее схожая дуга производительности',
    link: 'sims-career',
    type: 'table',
    id: 'sims-career',
    name: 'Баллы сходства.За карьеру',
  },
  {
    heading: null,
    link: 'all_college_stats',
    type: 'table',
    id: 'all_college_stats',
    name: 'Статистика колледжа',
  },
  { heading: null, link: 'all_salaries', type: 'table', id: 'all_salaries', name: 'Зарплаты' },
  {
    heading: null,
    link: 'awards',
    type: 'grid',
    id: 'div_leaderboard',
    name: 'Появление в списках лидеров, награды и почетные звания',
  },
  {
    heading: null,
    link: 'transactions',
    type: 'transactions',
    id: 'div_transactions',
    name: 'Транзакции',
  },
  {
    heading: null,
    link: 'contract',
    type: 'contract',
    id: 'div_contract',
    name: 'Текущий контракт',
  },
  {
    heading: null,
    link: 'faq',
    type: 'faq',
    id: 'div_faq',
    name: 'Часто задаваемые вопросы',
  },
];
