import { MasTeamsType } from 'mas';

export const masteamsyears: MasTeamsType[] = [
  {
    id: 'timeline_results',
    type: 'result',
    name: 'Результаты игр',
    link: '.html',
    heading: 'Высота столбика - перевес',
  },
  { id: 'roster', type: 'table', name: 'Реестр', link: '.html', heading: null },
  {
    id: 'div_assistant_coaches',
    type: 'coaches',
    name: 'Помощники тренеров и персонал',
    link: '.html',
    heading: null,
  },
  {
    id: 'team_and_opponent',
    type: 'table',
    name: 'Статистика команд и соперников',
    link: '.html',
    heading:
      'Рейтинги приведены по играм (за исключением MP, которые являются общими) и отсортированы по убыванию (за исключением TOV и PF); рейтинги соперников перевернуты; расчеты за год/год также приведены по играм',
  },
  { id: 'team_misc', type: 'table', name: 'Team misc', link: '.html', heading: null },
  { id: 'per_game', type: 'table', name: 'За игру.Регулярный сезон', link: '.html', heading: null },
  {
    id: 'playoffs_per_game',
    type: 'table',
    name: 'За игру.Плей-офф',
    link: '.html',
    heading: null,
  },
  { id: 'totals', type: 'table', name: 'Итоги.Регулярный сезон', link: '.html', heading: null },
  { id: 'playoffs_totals', type: 'table', name: 'Итоги.Плей-офф', link: '.html', heading: null },
  {
    id: 'per_minute',
    type: 'table',
    name: 'За 36 минут.Регулярный сезон',
    link: '.html',
    heading: null,
  },
  {
    id: 'playoffs_per_minute',
    type: 'table',
    name: 'За 36 минут.Плей-офф',
    link: '.html',
    heading: null,
  },
  {
    id: 'per_poss',
    type: 'table',
    name: 'За 100 владений мячом.Регулярный сезон',
    link: '.html',
    heading: null,
  },
  {
    id: 'playoffs_per_poss',
    type: 'table',
    name: 'За 100 владений мячом.Плей-офф',
    link: '.html',
    heading: null,
  },
  {
    id: 'advanced',
    type: 'table',
    name: 'Дополнительно.Регулярный сезон',
    link: '.html',
    heading: null,
  },
  {
    id: 'playoffs_advanced',
    type: 'table',
    name: 'Дополнительно.Плей-офф',
    link: '.html',
    heading: null,
  },
  {
    id: 'adj_shooting',
    type: 'table',
    name: 'Скорректированная стрельба.Регулярный сезон',
    link: '.html',
    heading: null,
  },
  { id: 'shooting', type: 'table', name: 'Броски.Регулярный сезон', link: '.html', heading: null },
  { id: 'playoffs_shooting', type: 'table', name: 'Броски.Плей-офф', link: '.html', heading: null },
  { id: 'pbp', type: 'table', name: 'Игра за игру.Регулярный сезон', link: '.html', heading: null },
  {
    id: 'playoffs_pbp',
    type: 'table',
    name: 'Игра за игру.Плей-офф',
    link: '.html',
    heading: null,
  },
  {
    id: 'div_leaderboard',
    type: 'grid',
    name: 'Игроки в таблице лидеров лиги',
    link: '.html',
    heading:
      'Включает в себя статистику за весь сезон для всех игроков, которые проводили время на площадке в регулярном чемпионате или плей-офф.',
  },
  { id: 'salaries2', type: 'table', name: 'Заработная плата', link: '.html', heading: null },
  { id: 'draft-rights', type: 'table', name: 'Драфт', link: '.html', heading: null },
  { id: 'div_faq', type: 'faq', name: 'Часто задаваемые вопросы', link: '.html', heading: null },
  {
    id: 'games',
    type: 'table',
    name: 'Расписание.Регулярный сезон',
    link: '_games.html',
    heading: null,
  },
  {
    id: 'games_playoffs',
    type: 'table',
    name: 'Расписание.Плей-офф',
    link: '_games.html',
    heading: null,
  },
  {
    id: 'page_index',
    type: 'transactions',
    name: 'Транзакции',
    link: '_transactions.html',
    heading: null,
  },
  {
    id: 'tgl_advanced',
    type: 'table',
    name: 'Игровой журнал.Регулярный сезон',
    link: '/gamelog-advanced/',
    heading: 'Обороты не включают командные обороты',
  },
  {
    id: 'tgl_advanced_playoffs',
    type: 'table',
    name: 'Игровой журнал.Плей-офф',
    link: '/gamelog-advanced/',
    heading: 'Обороты не включают командные обороты',
  },
  { id: 'team_splits', type: 'table', name: 'Разделение команд', link: '/splits/', heading: null },
  {
    id: 'lineups_5-man_',
    type: 'table',
    name: 'Комбинации из 5 человек.Регулярный сезон',
    link: '/lineups/',
    heading: null,
  },
  {
    id: 'lineups_4-man_',
    type: 'table',
    name: 'Комбинации из 4 человек.Регулярный сезон',
    link: '/lineups/',
    heading: null,
  },
  {
    id: 'lineups_3-man_',
    type: 'table',
    name: 'Комбинации из трех человек.Регулярный сезон',
    link: '/lineups/',
    heading: null,
  },
  {
    id: 'lineups_2-man_',
    type: 'table',
    name: 'Комбинации из двух человек.Регулярный сезон',
    link: '/lineups/',
    heading: null,
  },
  {
    id: 'lineups_5-man__p',
    type: 'table',
    name: 'Комбинации из 5 человек.Плей-офф',
    link: '/lineups/',
    heading: null,
  },
  {
    id: 'lineups_4-man__p',
    type: 'table',
    name: 'Комбинации из 4 человек.Плей-офф',
    link: '/lineups/',
    heading: null,
  },
  {
    id: 'lineups_3-man__p',
    type: 'table',
    name: 'Комбинации из трех человек.Плей-офф',
    link: '/lineups/',
    heading: null,
  },
  {
    id: 'lineups_2-man__p',
    type: 'table',
    name: 'Комбинации из двух человек.Плей-офф',
    link: '/lineups/',
    heading: null,
  },
  { id: 'on_off', type: 'table', name: 'On/Off.Регулярный сезон', link: '/on-off/', heading: null },
  { id: 'on_off_p', type: 'table', name: 'On/Off.Плей-офф', link: '/on-off/', heading: null },
  {
    id: 'starting_lineups_po0',
    type: 'table',
    name: 'Стартовые составы.Регулярный сезон 1',
    link: '_start.html',
    heading: null,
  },
  {
    id: 'starting_lineups_summary_po0',
    type: 'table',
    name: 'Стартовые составы.Регулярный сезон 2',
    link: '_start.html',
    heading: null,
  },
  {
    id: 'starting_lineups_po1',
    type: 'table',
    name: 'Стартовые составы.Плей-офф 1',
    link: '_start.html',
    heading: null,
  },
  {
    id: 'starting_lineups_summary_po1',
    type: 'table',
    name: 'Стартовые составы.Плей-офф 2',
    link: '_start.html',
    heading: null,
  },
  {
    id: 'div_depth_chart',
    type: 'chart',
    name: 'Глубинная диаграмма',
    link: '_depth.html',
    heading: null,
  },
  { id: 'refs-summary', type: 'table', name: 'Судьи', link: '_referees.html', heading: null },
];
