import { MasType } from 'mas';

export const masteamspages: MasType[] = [
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Командная статистика.Базовая',
    link: 'stats_basic_totals.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Командная статистика за игру.Базовая',
    link: 'stats_per_game_totals.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Статистика соперников.Базовая',
    link: 'opp_stats_basic_totals.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Статистика соперников за игру.Базовая',
    link: 'opp_stats_per_game_totals.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Командная статистика.Рейтинг лиги',
    link: 'stats_basic_ranks.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Командная статистика за игру.Рейтинг лиги',
    link: 'stats_per_game_ranks.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Статистика соперников.Рейтинг лиги',
    link: 'opp_stats_basic_ranks.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Статистика соперников за игру.Рейтинг лиги',
    link: 'opp_stats_per_game_ranks.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Командная статистика.В годовом исчислении',
    link: 'stats_basic_yr_yr.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Командная статистика за игру.В годовом исчислении',
    link: 'stats_per_game_yr_yr.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Статистика соперников.В годовом исчислении',
    link: 'opp_stats_basic_yr_yr.html',
  },
  {
    heading: null,
    id: 'stats',
    type: 'table',
    name: 'Статистика соперников за игру.В годовом исчислении',
    link: 'opp_stats_per_game_yr_yr.html',
  },
  {
    heading: '* - участник Зала славы',
    id: 'div_leaders',
    type: 'grid',
    name: 'Сезонные лидеры',
    link: 'leaders_season.html',
  },
  {
    heading: '* - участник Зала славы',
    id: 'div_leaders',
    type: 'grid',
    name: 'Карьерные лидеры',
    link: 'leaders_career.html',
  },
  {
    heading: 'Статистика приведена за время работы игрока во франшизе',
    id: 'franchise_register',
    type: 'table',
    name: 'Игроки',
    link: 'players.html',
  },
  {
    heading: 'Статистика приведена за время работы тренера во франшизе',
    id: 'coaches',
    type: 'table',
    name: 'Тренеры',
    link: 'coaches.html',
  },
  {
    heading:
      'В списке указаны только те руководители, которые отвечают за принятие кадровых решений по игрокам (обычно это генеральный менеджер).',
    id: 'executives',
    type: 'table',
    name: 'Руководители',
    link: 'executives.html',
  },
  {
    heading: null,
    id: 'div_leaderboard',
    type: 'grid',
    name: 'Матчи всех звезд',
    link: 'all_star.html',
  },
  {
    heading: 'Включает членов Зала славы, введенных в него в качестве игроков',
    id: 'div_leaderboard',
    type: 'grid',
    name: 'Зал славы',
    link: 'hof.html',
  },
  {
    heading:
      'Показанная статистика относится к карьере игрока в НБА ↳ указывает на последующие сделки.',
    id: 'draft',
    type: 'table',
    name: 'Драфт',
    link: 'draft.html',
  },
  {
    heading: null,
    id: 'div_leaderboard',
    type: 'grid',
    name: 'Номера униформ',
    link: 'numbers.html',
  },
  { heading: null, id: 'head2head', type: 'table', name: 'Взаимодействие', link: 'head2head.html' },
];
